[package]
name = "expandable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
expandable-impl = { path    = "expandable-impl" }
proc-macro2 = "1.0.66"
quote = "1.0"
# TODO: we don't actually use much of `syn` - how hard would it be to remove it?
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
trybuild = "1.0"